name: New Blueprint
description: Submit a new Blueprint
title: '[Blueprint] '
labels: ['blueprint']
assignees: 'CollinHeist'

body:
  - type: input
    id: series_name
    attributes:
      label: Series Name
      description: What is the full name of the Series?
      placeholder: ex. The Wire
    validations:
      required: true

