name: Discord Notification

on:
  workflow_call:

jobs:
  notify_discord:
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: refs/heads/staging
          persist-credentials: false
          fetch-depth: 0

      # Run script to parse issue
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Send Discord Message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_AVATAR: https://raw.githubusercontent.com/CollinHeist/static/main/logo.png
          ISSUES: "[${{ toJson(github.event.issue.body) }}]"
          ISSUE_CREATOR: '${{ github.event.issue.user.login }}'
          ISSUE_CREATOR_ICON_URL: '${{ github.event.issue.user.avatar_url }}'
        run: |
          python entrypoint.py --notify-discord
